occmundial/occ-atomic

CHANGELOG.md, lib/Autocomplete/__snapshots__/Autocomplete.test.js.snap, lib/Droplist/Droplist.js, lib/Droplist/__snapshots__/Droplist.test.js.snap, lib/Droplist/styles.js, package.json, src/docs/examples/Autocomplete/Example5.js
* Add new prop on droplist items to display any extra text en the list
* Change color in droplist Icons
* Update snapshots
=> Extra content droplist

lib/TextField/TextField.js, lib/TextField/styles.js
Se evitan múltiples lineas en TextField disabled
=> TextField disabled

CHANGELOG.md, lib/Footer/Footer.js, package.json
Se agrega condición para no agregar estilo en mobile
=> Fix mobile styles in footer

CHANGELOG.md, lib/Tag/styles.js, package.json
set correct margins in tags 
##before
##after
=> correct paddings in tags

CHANGELOG.md, lib/Icon/Icon.js, lib/Icon/__snapshots__/Icon.test.js.snap
Se cambia propiedad `name` por `ariaLabel` en componente Icon.
=> Change prop Icon

CHANGELOG.md, package.json
Se corrige versión en CHANGELOG.md por cambio de prop ariaLabel en componente Icon.
=> Fix version

CHANGELOG.md, lib/Footer/List/List.js, lib/Footer/__snapshots__/Footer.test.js.snap, package-lock.json, package.json
Se asigna valor de `ariaLabel `para elementos <Icon> en` Footer->List`
=> renderIcon aria label

CHANGELOG.md, lib/Footer/Footer.js, lib/Footer/List/List.js, lib/Footer/__snapshots__/Footer.test.js.snap, package.json
add a new prop to set a custom class in footer lists
=> list classname

CHANGELOG.md, lib/Button/Button.js, package.json
* Change propType in child prop button
* Format code with prettier
=> change propType in child prop button

package.json, src/docs/CodeExample/CodeExample.js, webpack.config.prod.js, yarn.lock
Upgrade to Webpack 5. Changing Uglify to Terser
=> Webpack upgrade

CHANGELOG.md, lib/subatomic/icons.js, lib/subatomic/icons/location.js, package.json
=> Add new icon 

CHANGELOG.md, package.json, src/docs/examples/Droplist/Example1.js, webpack.config.dev.js, webpack.config.prod.js
* Add Buffer in webpack plugins.
* Add icon on DropList examples to review if the new icons were compiled 
* Format code with prettier 
https://github.com/webpack/changelog-v5/issues/10
=> add Buffer to webpack 5 plugins

CHANGELOG.md, package.json
=> downgrade version

lib/Radio/Radio.js
Se añade el property de testId al componente del radio button para la creación de pruebas automatizadas.
=> feat: Add testId to radio button component

lib/Text/Text.js
- Se agrega el prop dataId al componente Text.
=> feat: Add testId to text component

lib/Radio/Radio.js, lib/SlideToggle/SlideToggle.js
- Add testid and data value to slidetoggle component
- Add data value to radio component
=> Radio slide testid

lib/Droplist/Droplist.js
- Se corrige la propiedad data-testid para el Autocomplete
=> fix: data-testid in Droplist

lib/SlideDown/SlideDown.js
Se agrega propiedad `noJustified ` a componente `<SlideDown>`
=> feat: Add noJustified to SlideDown component

lib/tokens/fonts.json
=> Update design tokens

lib/Tag/__snapshots__/Tag.test.js.snap, lib/Tag/styles.js
https://dev.azure.com/occmundial/Proyectos/_sprints/taskboard/Expert%20Team/Proyectos/ET%20-%20Sprint%206?workitem=32083
Changed outlines to borders.
=> feat:  Changed tag border to outline

lib/Tag/__snapshots__/Tag.test.js.snap, lib/Tag/styles.js
https://dev.azure.com/occmundial/Proyectos/_sprints/taskboard/Expert%20Team/Proyectos/ET%20-%20Sprint%206?workitem=32154
Remove extra padding in the label
=> fix: Remove extra padding in label
